// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPrice struct {
	Timestamp             string `json:"timestamp"`
	Low                   string `json:"low"`
	High                  string `json:"high"`
	Last                  string `json:"last"`
	Volume                string `json:"volume"`
	Volume30d             string `json:"volume30d"`
	PriceChange           string `json:"priceChange"`
	PriceChangePercentage string `json:"priceChangePercentage"`
	Pair                  string `json:"pair"`
}

type NewToken struct {
	Symbol    string `json:"symbol"`
	Usdprice  string `json:"usdprice"`
	Europrice string `json:"europrice"`
	Nokprice  string `json:"nokprice"`
}

type Price struct {
	Timestamp             string `json:"timestamp"`
	Low                   string `json:"low"`
	High                  string `json:"high"`
	Last                  string `json:"last"`
	Volume                string `json:"volume"`
	Volume30d             string `json:"volume30d"`
	PriceChange           string `json:"priceChange"`
	PriceChangePercentage string `json:"priceChangePercentage"`
	Pair                  string `json:"pair"`
}

type Token struct {
	ID        string `json:"id"`
	Symbol    string `json:"symbol"`
	Usdprice  string `json:"usdprice"`
	Europrice string `json:"europrice"`
	Nokprice  string `json:"nokprice"`
	Timestamp string `json:"timestamp"`
}
